name: Download and Extract MoltenVK
inputs:
  os:
    required: true
  cwd:
    default: .
runs:
  using: composite
  steps:
    - shell: bash
      if: inputs.os == 'macos-latest'
      run: |
        wget https://github.com/m4c0/molten-vk-build/releases/download/v1.2.2/MoltenVK.tgz
        tar zxf MoltenVK.tgz
        mv Package/Release/MoltenVK/MoltenVK.xcframework ${{ inputs.cwd }}

