name: Build on all platforms
on:
- push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone the MoltenVK repository
        run: git clone --depth=1 --branch v1.2.2 https://github.com/KhronosGroup/MoltenVK.git
      - name: Retrieve and build the external libraries
        run: ./fetchDependencies --all
        working-directory: MoltenVK
      - name: Building from the Command Line
        run: make all
        working-directory: MoltenVK
      - name: Install
        run: sudo make install
        working-directory: MoltenVK
      - name: Zips the output framework
        run: tar zcfv MoltenVK.tgz Package
        working-directory: MoltenVK
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v1.2.2
          release_name: Release v1.2.2
          draft: false
          prerelease: false
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: MoltenVK/MoltenVK.tgz
          asset_name: MoltenVK.tgz
          asset_content_type: application/tar+gzip
      - name: Test exposed GHA
        uses: ./.github/actions/setup
        with:
          os: macos-latest
          cwd: test

